version: '3.0'

# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:
  population_size: 100000

actions:

### exploratory analysis 

  generate_flow_chart_data_older_adults_s1:
    run: >
      ehrql:v1 generate-dataset analysis/dataset_definition_flow_chart.py
      --output output/older_adults_2016_2017_flow_chart.arrow
      -- older_adults season1_start_date season1_end_date
    outputs:
      highly_sensitive:
        dataset: output/older_adults_2016_2017_flow_chart.arrow

# ### primary analysis
# 
# ##  season 1 (2016/17)
# 
#   generate_dataset_older_adults_s1_spec:
#     run: >
#       ehrql:v1 generate-dataset analysis/dataset_definition.py
#       --output output/input_older_adults_2016_2017_specific_primary.arrow
#       --dummy-data-file analysis/dummydata/dummyextract_older_adults_2016_2017.arrow
#       -- older_adults season1_start_date season1_end_date specific primary
#     outputs:
#       highly_sensitive:
#         dataset: output/input_older_adults_2016_2017_specific_primary.arrow
# 
#   process_dataset_older_adults_s1_spec:
#     run: r:latest analysis/data_processing.R older_adults season1_start_date season1_end_date specific primary
#     needs: [generate_dataset_older_adults_s1_spec]
#     outputs:
#       highly_sensitive:
#         cohort: output/input_processed_older_adults_2016_2017_specific_primary.arrow
# 
#   describe_dataset_older_adults_s1_spec:
#     run: r:latest analysis/report.R older_adults season1_start_date season1_end_date specific primary
#     needs: [process_dataset_older_adults_s1_spec]
#     outputs:
#       moderately_sensitive:
#         png: output/descriptive_older_adults_2016_2017_specific_primary.png
#         html: output/table1_older_adults_2016_2017_specific_primary.html
#         csv: output/table1_older_adults_2016_2017_specific_primary.csv
# 
#   generate_dataset_adults_s1_spec:
#     run: >
#       ehrql:v1 generate-dataset analysis/dataset_definition.py
#       --output output/input_adults_2016_2017_specific_primary.arrow
#       --dummy-data-file analysis/dummydata/dummyextract_adults_2016_2017.arrow
#       -- adults season1_start_date season1_end_date specific primary
#     outputs:
#       highly_sensitive:
#         dataset: output/input_adults_2016_2017_specific_primary.arrow
# 
#   process_dataset_adults_s1_spec:
#     run: r:latest analysis/data_processing.R adults season1_start_date season1_end_date specific primary
#     needs: [generate_dataset_adults_s1_spec]
#     outputs:
#       highly_sensitive:
#         cohort: output/input_processed_adults_2016_2017_specific_primary.arrow
# 
#   describe_dataset_adults_s1_spec:
#     run: r:latest analysis/report.R adults season1_start_date season1_end_date specific primary
#     needs: [process_dataset_adults_s1_spec]
#     outputs:
#       moderately_sensitive:
#         png: output/descriptive_adults_2016_2017_specific_primary.png
#         html: output/table1_adults_2016_2017_specific_primary.html
#         csv: output/table1_adults_2016_2017_specific_primary.csv
# 
#   generate_dataset_children_and_adolescents_s1_spec:
#     run: >
#       ehrql:v1 generate-dataset analysis/dataset_definition.py
#       --output output/input_children_and_adolescents_2016_2017_specific_primary.arrow
#       --dummy-data-file analysis/dummydata/dummyextract_children_and_adolescents_2016_2017.arrow
#       -- children_and_adolescents season1_start_date season1_end_date specific primary
#     outputs:
#       highly_sensitive:
#         dataset: output/input_children_and_adolescents_2016_2017_specific_primary.arrow
# 
#   process_dataset_children_and_adolescents_s1_spec:
#     run: r:latest analysis/data_processing.R children_and_adolescents season1_start_date season1_end_date specific primary
#     needs: [generate_dataset_children_and_adolescents_s1_spec]
#     outputs:
#       highly_sensitive:
#         cohort: output/input_processed_children_and_adolescents_2016_2017_specific_primary.arrow
# 
#   describe_dataset_children_and_adolescents_s1_spec:
#     run: r:latest analysis/report.R children_and_adolescents season1_start_date season1_end_date specific primary
#     needs: [process_dataset_children_and_adolescents_s1_spec]
#     outputs:
#       moderately_sensitive:
#         png: output/descriptive_children_and_adolescents_2016_2017_specific_primary.png
#         html: output/table1_children_and_adolescents_2016_2017_specific_primary.html
#         csv: output/table1_children_and_adolescents_2016_2017_specific_primary.csv
# 
#   generate_dataset_infants_s1_spec:
#     run: >
#       ehrql:v1 generate-dataset analysis/dataset_definition.py
#       --output output/input_infants_2016_2017_specific_primary.arrow
#       --dummy-data-file analysis/dummydata/dummyextract_infants_2016_2017.arrow
#       -- infants season1_start_date season1_end_date specific primary
#     outputs:
#       highly_sensitive:
#         dataset: output/input_infants_2016_2017_specific_primary.arrow
# 
#   process_dataset_infants_s1_spec:
#     run: r:latest analysis/data_processing.R infants season1_start_date season1_end_date specific primary
#     needs: [generate_dataset_infants_s1_spec]
#     outputs:
#       highly_sensitive:
#         cohort: output/input_processed_infants_2016_2017_specific_primary.arrow
# 
#   describe_dataset_infants_s1_spec:
#     run: r:latest analysis/report.R infants season1_start_date season1_end_date specific primary
#     needs: [process_dataset_infants_s1_spec]
#     outputs:
#       moderately_sensitive:
#         png: output/descriptive_infants_2016_2017_specific_primary.png
#         html: output/table1_infants_2016_2017_specific_primary.html
#         csv: output/table1_infants_2016_2017_specific_primary.csv
# 
# ### sensitivity analysis
# 
# ##  season 1 (2016/17)
# 
#   generate_dataset_older_adults_s1_sens:
#     run: >
#       ehrql:v1 generate-dataset analysis/dataset_definition.py
#       --output output/input_older_adults_2016_2017_sensitive_primary.arrow
#       --dummy-data-file analysis/dummydata/dummyextract_older_adults_2016_2017.arrow
#       -- older_adults season1_start_date season1_end_date sensitive primary
#     outputs:
#       highly_sensitive:
#         dataset: output/input_older_adults_2016_2017_sensitive_primary.arrow
# 
#   process_dataset_older_adults_s1_sens:
#     run: r:latest analysis/data_processing.R older_adults season1_start_date season1_end_date sensitive primary
#     needs: [generate_dataset_older_adults_s1_sens]
#     outputs:
#       highly_sensitive:
#         cohort: output/input_processed_older_adults_2016_2017_sensitive_primary.arrow
# 
#   describe_dataset_older_adults_s1_sens:
#     run: r:latest analysis/report.R older_adults season1_start_date season1_end_date sensitive primary
#     needs: [process_dataset_older_adults_s1_sens]
#     outputs:
#       moderately_sensitive:
#         png: output/descriptive_older_adults_2016_2017_sensitive_primary.png
#         html: output/table1_older_adults_2016_2017_sensitive_primary.html
#         csv: output/table1_older_adults_2016_2017_sensitive_primary.csv
# 
#   generate_dataset_adults_s1_sens:
#     run: >
#       ehrql:v1 generate-dataset analysis/dataset_definition.py
#       --output output/input_adults_2016_2017_sensitive_primary.arrow
#       --dummy-data-file analysis/dummydata/dummyextract_adults_2016_2017.arrow
#       -- adults season1_start_date season1_end_date sensitive primary
#     outputs:
#       highly_sensitive:
#         dataset: output/input_adults_2016_2017_sensitive_primary.arrow
# 
#   process_dataset_adults_s1_sens:
#     run: r:latest analysis/data_processing.R adults season1_start_date season1_end_date sensitive primary
#     needs: [generate_dataset_adults_s1_sens]
#     outputs:
#       highly_sensitive:
#         cohort: output/input_processed_adults_2016_2017_sensitive_primary.arrow
# 
#   describe_dataset_adults_s1_sens:
#     run: r:latest analysis/report.R adults season1_start_date season1_end_date sensitive primary
#     needs: [process_dataset_adults_s1_sens]
#     outputs:
#       moderately_sensitive:
#         png: output/descriptive_adults_2016_2017_sensitive_primary.png
#         html: output/table1_adults_2016_2017_sensitive_primary.html
#         csv: output/table1_adults_2016_2017_sensitive_primary.csv
# 
#   generate_dataset_children_and_adolescents_s1_sens:
#     run: >
#       ehrql:v1 generate-dataset analysis/dataset_definition.py
#       --output output/input_children_and_adolescents_2016_2017_sensitive_primary.arrow
#       --dummy-data-file analysis/dummydata/dummyextract_children_and_adolescents_2016_2017.arrow
#       -- children_and_adolescents season1_start_date season1_end_date sensitive primary
#     outputs:
#       highly_sensitive:
#         dataset: output/input_children_and_adolescents_2016_2017_sensitive_primary.arrow
# 
#   process_dataset_children_and_adolescents_s1_sens:
#     run: r:latest analysis/data_processing.R children_and_adolescents season1_start_date season1_end_date sensitive primary
#     needs: [generate_dataset_children_and_adolescents_s1_sens]
#     outputs:
#       highly_sensitive:
#         cohort: output/input_processed_children_and_adolescents_2016_2017_sensitive_primary.arrow
# 
#   describe_dataset_children_and_adolescents_s1_sens:
#     run: r:latest analysis/report.R children_and_adolescents season1_start_date season1_end_date sensitive primary
#     needs: [process_dataset_children_and_adolescents_s1_sens]
#     outputs:
#       moderately_sensitive:
#         png: output/descriptive_children_and_adolescents_2016_2017_sensitive_primary.png
#         html: output/table1_children_and_adolescents_2016_2017_sensitive_primary.html
#         csv: output/table1_children_and_adolescents_2016_2017_sensitive_primary.csv
# 
#   generate_dataset_infants_s1_sens:
#     run: >
#       ehrql:v1 generate-dataset analysis/dataset_definition.py
#       --output output/input_infants_2016_2017_sensitive_primary.arrow
#       --dummy-data-file analysis/dummydata/dummyextract_infants_2016_2017.arrow
#       -- infants season1_start_date season1_end_date sensitive primary
#     outputs:
#       highly_sensitive:
#         dataset: output/input_infants_2016_2017_sensitive_primary.arrow
# 
#   process_dataset_infants_s1_sens:
#     run: r:latest analysis/data_processing.R infants season1_start_date season1_end_date sensitive primary
#     needs: [generate_dataset_infants_s1_sens]
#     outputs:
#       highly_sensitive:
#         cohort: output/input_processed_infants_2016_2017_sensitive_primary.arrow
# 
#   describe_dataset_infants_s1_sens:
#     run: r:latest analysis/report.R infants season1_start_date season1_end_date sensitive primary
#     needs: [process_dataset_infants_s1_sens]
#     outputs:
#       moderately_sensitive:
#         png: output/descriptive_infants_2016_2017_sensitive_primary.png
#         html: output/table1_infants_2016_2017_sensitive_primary.html
#         csv: output/table1_infants_2016_2017_sensitive_primary.csv
# 
# ### secondary analysis
# 
# ##  season 1 (2016/17)
# 
#   generate_dataset_older_adults_s1_sens_sec:
#     run: >
#       ehrql:v1 generate-dataset analysis/dataset_definition.py
#       --output output/input_older_adults_2016_2017_sensitive_secondary.arrow
#       --dummy-data-file analysis/dummydata/dummyextract_older_adults_2016_2017.arrow
#       -- older_adults season1_start_date season1_end_date sensitive secondary
#     outputs:
#       highly_sensitive:
#         dataset: output/input_older_adults_2016_2017_sensitive_secondary.arrow
# 
#   process_dataset_older_adults_s1_sens_sec:
#     run: r:latest analysis/data_processing.R older_adults season1_start_date season1_end_date sensitive secondary
#     needs: [generate_dataset_older_adults_s1_sens_sec]
#     outputs:
#       highly_sensitive:
#         cohort: output/input_processed_older_adults_2016_2017_sensitive_secondary.arrow
#  
#   describe_dataset_older_adults_s1_sens_sec:
#     run: r:latest analysis/report.R older_adults season1_start_date season1_end_date sensitive secondary
#     needs: [process_dataset_older_adults_s1_sens_sec]
#     outputs:
#       moderately_sensitive:
#         png: output/descriptive_older_adults_2016_2017_sensitive_secondary.png
#         html: output/table1_older_adults_2016_2017_sensitive_secondary.html
#         csv: output/table1_older_adults_2016_2017_sensitive_secondary.csv
# 
#   generate_dataset_adults_s1_sens_sec:
#     run: >
#       ehrql:v1 generate-dataset analysis/dataset_definition.py
#       --output output/input_adults_2016_2017_sensitive_secondary.arrow
#       --dummy-data-file analysis/dummydata/dummyextract_adults_2016_2017.arrow
#       -- adults season1_start_date season1_end_date sensitive secondary
#     outputs:
#       highly_sensitive:
#         dataset: output/input_adults_2016_2017_sensitive_secondary.arrow
# 
#   process_dataset_adults_s1_sens_sec:
#     run: r:latest analysis/data_processing.R adults season1_start_date season1_end_date sensitive secondary
#     needs: [generate_dataset_adults_s1_sens_sec]
#     outputs:
#       highly_sensitive:
#         cohort: output/input_processed_adults_2016_2017_sensitive_secondary.arrow
#  
#   describe_dataset_adults_s1_sens_sec:
#     run: r:latest analysis/report.R adults season1_start_date season1_end_date sensitive secondary
#     needs: [process_dataset_adults_s1_sens_sec]
#     outputs:
#       moderately_sensitive:
#         png: output/descriptive_adults_2016_2017_sensitive_secondary.png
#         html: output/table1_adults_2016_2017_sensitive_secondary.html
#         csv: output/table1_adults_2016_2017_sensitive_secondary.csv
# 
#   generate_dataset_children_and_adolescents_s1_sens_sec:
#     run: >
#       ehrql:v1 generate-dataset analysis/dataset_definition.py
#       --output output/input_children_and_adolescents_2016_2017_sensitive_secondary.arrow
#       --dummy-data-file analysis/dummydata/dummyextract_children_and_adolescents_2016_2017.arrow
#       -- children_and_adolescents season1_start_date season1_end_date sensitive secondary
#     outputs:
#       highly_sensitive:
#         dataset: output/input_children_and_adolescents_2016_2017_sensitive_secondary.arrow
# 
#   process_dataset_children_and_adolescents_s1_sens_sec:
#     run: r:latest analysis/data_processing.R children_and_adolescents season1_start_date season1_end_date sensitive secondary
#     needs: [generate_dataset_children_and_adolescents_s1_sens_sec]
#     outputs:
#       highly_sensitive:
#         cohort: output/input_processed_children_and_adolescents_2016_2017_sensitive_secondary.arrow
#  
#   describe_dataset_children_and_adolescents_s1_sens_sec:
#     run: r:latest analysis/report.R children_and_adolescents season1_start_date season1_end_date sensitive secondary
#     needs: [process_dataset_children_and_adolescents_s1_sens_sec]
#     outputs:
#       moderately_sensitive:
#         png: output/descriptive_children_and_adolescents_2016_2017_sensitive_secondary.png
#         html: output/table1_children_and_adolescents_2016_2017_sensitive_secondary.html
#         csv: output/table1_children_and_adolescents_2016_2017_sensitive_secondary.csv
# 
#   generate_dataset_infants_s1_sens_sec:
#     run: >
#       ehrql:v1 generate-dataset analysis/dataset_definition.py
#       --output output/input_infants_2016_2017_sensitive_secondary.arrow
#       --dummy-data-file analysis/dummydata/dummyextract_infants_2016_2017.arrow
#       -- infants season1_start_date season1_end_date sensitive secondary
#     outputs:
#       highly_sensitive:
#         dataset: output/input_infants_2016_2017_sensitive_secondary.arrow
# 
#   process_dataset_infants_s1_sens_sec:
#     run: r:latest analysis/data_processing.R infants season1_start_date season1_end_date sensitive secondary
#     needs: [generate_dataset_infants_s1_sens_sec]
#     outputs:
#       highly_sensitive:
#         cohort: output/input_processed_infants_2016_2017_sensitive_secondary.arrow
# 
#   describe_dataset_infants_s1_sens_sec:
#     run: r:latest analysis/report.R infants season1_start_date season1_end_date sensitive secondary
#     needs: [process_dataset_infants_s1_sens_sec]
#     outputs:
#       moderately_sensitive:
#         png: output/descriptive_infants_2016_2017_sensitive_secondary.png
#         html: output/table1_infants_2016_2017_sensitive_secondary.html
#         csv: output/table1_infants_2016_2017_sensitive_secondary.csv
#   